name: Intaract with Google Drive
description: Upload/Download files to/from Google Drive
branding:
  icon: upload-cloud
  color: gray-dark
inputs:
  skicka-tokencache-json:
    description: Content of `~/.skicka.tokencache.json` created by the `skicka` command
    required: true
  upload-from:
    description: The path where the files to upload are located
    default: ./
    required: false
  upload-to:
    description: The path where the files to be uploaded is located
    required: false
  download-from:
    description: The path where the files to download are located
    required: false
  download-to:
    description: The path where the files to be downloaded is located
    required: false
    default: ./
  remove-outdated:
    description: Whether to delete files that do not exist locally
    default: 'true'
    required: false
  google-client-id:
    description: Your Google Drive API client ID
    required: false
  google-client-secret:
    description: Your Google Drive API client secret
    required: false
runs:
  using: docker
  image: >-
    docker://docker.io/satackey/action-google-drive:417d5ac482ae9c22db61470588f1b2a665cf258a
  env:
    SKICKA_TOKENCACHE_JSON: '${{ inputs.skicka-tokencache-json }}'
    UPLOAD_FROM: '${{ inputs.upload-from }}'
    UPLOAD_TO: '${{ inputs.upload-to }}'
    DOWNLOAD_FROM: '${{ inputs.download-from }}'
    DOWNLOAD_TO: '${{ inputs.download-to }}'
    REMOVE_OUTDATED: '${{ inputs.remove-outdated }}'
    GOOGLE_CLIENT_ID: '${{ inputs.google-client-id }}'
    GOOGLE_CLIENT_SECRET: '${{ inputs.google-client-secret }}'
